---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gocusign-stg-back
  namespace: gocusign-stg
  labels:
    app: gocusign-stg-back
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  replicas: 1
  selector:
    matchLabels:
      app: gocusign-stg-back
  template:
    metadata:
      labels:
        app: gocusign-stg-back
    spec:
      containers:
      - name: gocusign-stg-back
        image: 197272534240.dkr.ecr.us-east-1.amazonaws.com/gocusign-stg:{{BUILD_NUMBER}}
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 400Mi
          requests:
            cpu: 80m
            memory: 150Mi
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: gocusign-stg-config
        volumeMounts:
          - name: config
            mountPath: /etc/localtime
      volumes:
        - name: config
          hostPath:
            path: /usr/share/zoneinfo/America/Sao_Paulo