FROM golang:1.25.9-bookworm

ARG PROJECT_NAME="app"
ARG VERSION="dev"
ARG COMMIT="none"
ENV CGO_ENABLED=0
ENV GOPROXY=https://proxy.golang.org

COPY . /app/
WORKDIR /app
RUN go mod download
RUN go install github.com/pilu/fresh@latest

EXPOSE 8080

CMD ["fresh"]
